name: Every 5 Minutes Cron

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta todos los d√≠as a las 00:00 UTC

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Node 1
        run: curl -X GET https://not-centralized-node-1.onrender.com/sync
      - name: Sync Node 2
        run: curl -X GET https://not-centralized-node-2.onrender.com/sync
      - name: Sync Node 3
        run: curl -X GET https://not-centralized-node-3.onrender.com/sync
